/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import javax.swing.JOptionPane;

/**
 *
 * @author yogan
 */
public class menu_kasir extends javax.swing.JFrame {

    /**
     * Creates new form menu_kasir
     */
    public menu_kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nama_kasir = new javax.swing.JLabel();
        kasir4 = new javax.swing.JLabel();
        kasir1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kasir3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        nama_kasir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nama_kasir.setForeground(new java.awt.Color(36, 36, 36));
        nama_kasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/user_40px.png"))); // NOI18N
        nama_kasir.setIconTextGap(20);
        jPanel1.add(nama_kasir);
        nama_kasir.setBounds(290, 50, 600, 60);

        kasir4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kasir4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kasir4MouseClicked(evt);
            }
        });
        jPanel1.add(kasir4);
        kasir4.setBounds(670, 420, 270, 170);

        kasir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kasir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kasir1MouseClicked(evt);
            }
        });
        jPanel1.add(kasir1);
        kasir1.setBounds(350, 200, 260, 160);

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(670, 190, 270, 170);

        kasir3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kasir3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kasir3MouseClicked(evt);
            }
        });
        jPanel1.add(kasir3);
        kasir3.setBounds(350, 420, 260, 170);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Logout_40px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(950, 50, 50, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/menu.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kasir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasir1MouseClicked
        // TODO add your handling code here:
        kasir.transaksi nama= new kasir.transaksi();
        nama.namakasir.setText(nama_kasir.getText());
         
        nama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kasir1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
         kasir.edit_barang nama= new kasir.edit_barang();
        nama.namakasir.setText(nama_kasir.getText());
         
        nama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void kasir3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasir3MouseClicked
        // TODO add your handling code here:
         kasir.Statistik nama= new kasir.Statistik();
        nama.namakasir.setText(nama_kasir.getText());
         
        nama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kasir3MouseClicked

    private void kasir4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasir4MouseClicked
        // TODO add your handling code here:
         kasir.riwayat nama= new kasir.riwayat();
        nama.namakasir.setText(nama_kasir.getText());
         
        nama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kasir4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
//        this.setVisible(false);
        int response = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new login.login().setVisible(true);
        } else if (response == JOptionPane.NO_OPTION) {
            
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel kasir1;
    public javax.swing.JLabel kasir3;
    private javax.swing.JLabel kasir4;
    public javax.swing.JLabel nama_kasir;
    // End of variables declaration//GEN-END:variables
}
