/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import login.Config;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author yogan
 */
public class Popup_transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Popup_transaksi
     */
    public Popup_transaksi() {
        initComponents();
        load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        namaPelanggan = new javax.swing.JLabel();
        namaPegawai = new javax.swing.JLabel();
        gtot = new javax.swing.JLabel();
        bayarp = new javax.swing.JLabel();
        balik = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        trans = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 20));

        jPanel1.setBackground(new java.awt.Color(210, 230, 252));
        jPanel1.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/back_40px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(540, 20, 50, 50);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(36, 36, 36));
        jLabel32.setText("Rp.");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(320, 550, 30, 30);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(36, 36, 36));
        jLabel33.setText("Rp.");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(320, 610, 30, 30);

        namaPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        namaPelanggan.setForeground(new java.awt.Color(36, 36, 36));
        jPanel1.add(namaPelanggan);
        namaPelanggan.setBounds(230, 180, 240, 30);

        namaPegawai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        namaPegawai.setForeground(new java.awt.Color(36, 36, 36));
        jPanel1.add(namaPegawai);
        namaPegawai.setBounds(230, 220, 240, 30);

        gtot.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        gtot.setForeground(new java.awt.Color(36, 36, 36));
        jPanel1.add(gtot);
        gtot.setBounds(320, 510, 240, 30);

        bayarp.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bayarp.setForeground(new java.awt.Color(36, 36, 36));
        jPanel1.add(bayarp);
        bayarp.setBounds(350, 550, 210, 30);

        balik.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        balik.setForeground(new java.awt.Color(36, 36, 36));
        balik.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                balikAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(balik);
        balik.setBounds(350, 610, 210, 30);

        tanggal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tanggal.setForeground(new java.awt.Color(36, 36, 36));
        jPanel1.add(tanggal);
        tanggal.setBounds(230, 140, 240, 30);

        trans.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        trans.setForeground(new java.awt.Color(36, 36, 36));
        trans.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                transAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(trans);
        trans.setBounds(230, 100, 240, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 36, 36));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/logo 75.png"))); // NOI18N
        jLabel8.setText(" CV. JAYA MAJU");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(15, 10, 460, 75);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 36, 36));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bar.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(220, 100, 270, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 36, 36));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/purchase_order_25px.png"))); // NOI18N
        jLabel11.setText("No. Transaksi");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 100, 170, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(36, 36, 36));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/identification_documents_25px.png"))); // NOI18N
        jLabel12.setText("Pegawai");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 220, 170, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(36, 36, 36));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/calendar_25px.png"))); // NOI18N
        jLabel13.setText("Tgl. Transaksi");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 140, 170, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(36, 36, 36));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/price_25px.png"))); // NOI18N
        jLabel14.setText("Total Harga");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(160, 510, 130, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(36, 36, 36));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bar.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(310, 510, 270, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(36, 36, 36));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bar.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(220, 220, 270, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(36, 36, 36));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bar.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(220, 140, 270, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(36, 36, 36));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/user_25px.png"))); // NOI18N
        jLabel17.setText("Nama Pelanggan");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 180, 170, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(36, 36, 36));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bar.png"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(220, 180, 270, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(36, 36, 36));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/money_25px.png"))); // NOI18N
        jLabel20.setText("Bayar");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(210, 550, 80, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(36, 36, 36));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bar.png"))); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(310, 550, 270, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(260, 5));
        jPanel3.setPreferredSize(new java.awt.Dimension(260, 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(580, 590, 20, 10);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(260, 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(260, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(310, 590, 260, 10);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(36, 36, 36));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/coin_in_hand_25px.png"))); // NOI18N
        jLabel22.setText("Kembalian");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(170, 610, 120, 30);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(36, 36, 36));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bar.png"))); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(310, 610, 270, 30);

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(210, 230, 252));
        jTable1.setOpaque(false);
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 260, 540, 240);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/barpopup.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 600, 110);

        print.setBackground(new java.awt.Color(255, 255, 255));
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/print_75px.png"))); // NOI18N
        print.setBorder(null);
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.setOpaque(false);
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print);
        print.setBounds(30, 510, 110, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        kasir.transaksi nama= new kasir.transaksi();
        nama.namakasir.setText(namaPegawai.getText());
         
        nama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void transAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_transAncestorAdded
        // TODO add your handling code here:
        load_table();
    }//GEN-LAST:event_transAncestorAdded

    private void balikAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_balikAncestorAdded
        // TODO add your handling code here:
        String sbyr = balik.getText().replaceAll("\\,","");
        double dbyr = Double.parseDouble(sbyr);
        DecimalFormat df = new DecimalFormat("#,###,###");
        if(dbyr>999){
        balik.setText(df.format(dbyr));
        }
    }//GEN-LAST:event_balikAncestorAdded

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
        load_table();
    }//GEN-LAST:event_jTable1AncestorAdded

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try {
        java.sql.Connection conn=(Connection)Config.configDB();
//        String namafile = "src/kasir/report.jrxml";
        InputStream report = getClass().getResourceAsStream("report.jasper");
        HashMap param = new HashMap();
        param.put("kd_trans",trans.getText());
//        File file = new File(namafile);
//        JasperDesign jd = JRXmlLoader.load(namafile);
//        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(report,param,conn);
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    private void tablestyle() {
        JTableHeader style = jTable1.getTableHeader();
        jTable1.setRowHeight(25);
        TableColumn col=jTable1.getColumnModel().getColumn(0);
        col.setPreferredWidth(30);
        TableColumn col1=jTable1.getColumnModel().getColumn(1);
        col1.setPreferredWidth(100);
        TableColumn col2=jTable1.getColumnModel().getColumn(2);
        col2.setPreferredWidth(50);
        TableColumn col3=jTable1.getColumnModel().getColumn(3);
        col3.setPreferredWidth(30);
        TableColumn col4=jTable1.getColumnModel().getColumn(4);
        col4.setPreferredWidth(100);
    }
    private void load_table() {
    DefaultTableModel model = new DefaultTableModel();
    
    model.addColumn("No");
    model.addColumn("Nama Barang");
    model.addColumn("Jumlah");
    model.addColumn("Satuan");
    model.addColumn("Total Harga");


    
    try {
        int no=1;
        String sql = "SELECT barang.nama_barang, detail_tranksaksi.qty, detail_tranksaksi.id_satuan, detail_tranksaksi.harga_total from ((detail_tranksaksi inner join tranksaksi on detail_tranksaksi.id_tranksaksi=tranksaksi.id_tranksaksi) "
                +"inner join barang on detail_tranksaksi.id_barang=barang.id_barang)"
                + "where detail_tranksaksi.id_tranksaksi='"+trans.getText()+"' ;";
//        String sql = "SELECT * from detail_tranksaksi;";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
            model.addRow (new Object[] {no++,res.getString(1),
                res.getString(2),res.getString(3),this.formatRupiah((int) res.getDouble(4)).replace(",00", "")
            });
        }
        jTable1.setModel(model);
    } catch (Exception e) {
        
    }
    tablestyle();
    }
    private String formatRupiah(int value){
      DecimalFormat formater = (DecimalFormat) DecimalFormat.getCurrencyInstance();
      DecimalFormatSymbols simbol = formater.getDecimalFormatSymbols();
      
      simbol.setCurrencySymbol("Rp. ");
      simbol.setMonetaryDecimalSeparator(',');// belakang sendiri pada format rupiah
      simbol.setGroupingSeparator('.');
      formater.setDecimalFormatSymbols(simbol);
      return formater.format(value);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popup_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popup_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popup_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popup_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popup_transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel balik;
    public javax.swing.JLabel bayarp;
    public javax.swing.JLabel gtot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JLabel namaPegawai;
    public javax.swing.JLabel namaPelanggan;
    private javax.swing.JButton print;
    public javax.swing.JLabel tanggal;
    public javax.swing.JLabel trans;
    // End of variables declaration//GEN-END:variables
}
