/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import java.sql.Connection;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import login.Config;

/**
 *
 * @author yogan
 */
public class transaksi extends javax.swing.JFrame {

    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        load_table();
        load_table1();
        tablestyle();
        tablestyle1();
        AUTONOMORPENJUALAN();
        grand_total();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cart = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        btn_proses = new javax.swing.JButton();
        btn_addcart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namakasir = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        txtcari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txttransaksi = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        satuan = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        g_total = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kd_bar_cart = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        kd_bar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KasirKita ~ Transaksi");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel2.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel2.setLayout(null);

        nama.setBackground(new java.awt.Color(236, 236, 236));
        nama.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nama.setForeground(new java.awt.Color(36, 36, 36));
        nama.setBorder(null);
        nama.setOpaque(false);
        jPanel2.add(nama);
        nama.setBounds(460, 120, 260, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Logout_40px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(220, 60, 40, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 36, 36));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/money_25px.png"))); // NOI18N
        jLabel3.setText("Bayar");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(760, 570, 130, 30);

        tbl_cart.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbl_cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tbl_cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cart);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(760, 210, 460, 310);

        tbl_barang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_barang);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(292, 210, 430, 310);

        btn_proses.setBackground(new java.awt.Color(255, 255, 255));
        btn_proses.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_proses.setForeground(new java.awt.Color(36, 36, 36));
        btn_proses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Check Circle_25px.png"))); // NOI18N
        btn_proses.setText("Checkout");
        btn_proses.setBorder(null);
        btn_proses.setBorderPainted(false);
        btn_proses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_proses.setIconTextGap(2);
        btn_proses.setOpaque(false);
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });
        jPanel2.add(btn_proses);
        btn_proses.setBounds(1100, 530, 120, 80);

        btn_addcart.setBackground(new java.awt.Color(255, 255, 255));
        btn_addcart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_addcart.setForeground(new java.awt.Color(36, 36, 36));
        btn_addcart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/add_shopping_cart_25px.png"))); // NOI18N
        btn_addcart.setText("Add Cart");
        btn_addcart.setBorder(null);
        btn_addcart.setBorderPainted(false);
        btn_addcart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addcart.setOpaque(false);
        btn_addcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcartActionPerformed(evt);
            }
        });
        jPanel2.add(btn_addcart);
        btn_addcart.setBounds(590, 530, 130, 70);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 36, 36));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/shopping_cart_25px.png"))); // NOI18N
        jLabel4.setText("Cart");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(760, 170, 160, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 36, 36));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/price_25px.png"))); // NOI18N
        jLabel5.setText("Total Harga");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(760, 530, 120, 30);

        namakasir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        namakasir.setForeground(new java.awt.Color(36, 36, 36));
        jPanel2.add(namakasir);
        namakasir.setBounds(70, 60, 140, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 36, 36));
        jLabel6.setText("Jumlah");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(290, 530, 90, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 36, 36));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/search_25px.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(690, 170, 30, 30);

        bayar.setBackground(new java.awt.Color(236, 236, 236));
        bayar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bayar.setForeground(new java.awt.Color(36, 36, 36));
        bayar.setBorder(null);
        bayar.setOpaque(false);
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
        });
        jPanel2.add(bayar);
        bayar.setBounds(920, 570, 160, 30);

        txtcari.setBackground(new java.awt.Color(236, 236, 236));
        txtcari.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtcari.setForeground(new java.awt.Color(36, 36, 36));
        txtcari.setBorder(null);
        txtcari.setOpaque(false);
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });
        jPanel2.add(txtcari);
        txtcari.setBounds(460, 170, 230, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 36, 36));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/product_25px.png"))); // NOI18N
        jLabel9.setText("List Barang");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(290, 170, 160, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 36, 36));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/user_25px.png"))); // NOI18N
        jLabel10.setText("Nama pelanggan");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(290, 120, 160, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 36, 36));
        jLabel11.setText("Rp.");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(890, 570, 30, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(36, 36, 36));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/purchase_order_25px.png"))); // NOI18N
        jLabel12.setText("No. Transaksi");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(760, 120, 130, 30);

        txttransaksi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txttransaksi.setForeground(new java.awt.Color(36, 36, 36));
        txttransaksi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txttransaksiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(txttransaksi);
        txttransaksi.setBounds(910, 120, 70, 30);

        jam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jam.setForeground(new java.awt.Color(36, 36, 36));
        jam.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jamAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jam);
        jam.setBounds(1010, 120, 50, 30);

        tgl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tgl.setForeground(new java.awt.Color(36, 36, 36));
        tgl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tglAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(tgl);
        tgl.setBounds(1090, 120, 120, 30);

        satuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        satuan.setForeground(new java.awt.Color(36, 36, 36));
        jPanel2.add(satuan);
        satuan.setBounds(530, 530, 50, 30);

        jumlah.setBackground(new java.awt.Color(236, 236, 236));
        jumlah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jumlah.setForeground(new java.awt.Color(36, 36, 36));
        jumlah.setBorder(null);
        jumlah.setOpaque(false);
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahKeyReleased(evt);
            }
        });
        jPanel2.add(jumlah);
        jumlah.setBounds(390, 530, 140, 30);

        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18);
        jLabel18.setBounds(40, 400, 60, 50);

        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19);
        jLabel19.setBounds(40, 180, 60, 50);

        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20);
        jLabel20.setBounds(40, 250, 60, 50);

        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21);
        jLabel21.setBounds(40, 330, 60, 50);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/back_40px.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel22);
        jLabel22.setBounds(1190, 60, 50, 50);

        g_total.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        g_total.setForeground(new java.awt.Color(36, 36, 36));
        jPanel2.add(g_total);
        g_total.setBounds(890, 530, 190, 30);

        btn_delete.setBackground(new java.awt.Color(255, 255, 255));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(36, 36, 36));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/trash_25px.png"))); // NOI18N
        btn_delete.setBorder(null);
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.setOpaque(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_delete);
        btn_delete.setBounds(1160, 160, 60, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/transaksi.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);
        jPanel2.add(kd_bar_cart);
        kd_bar_cart.setBounds(70, 640, 0, 0);

        harga.setBackground(new java.awt.Color(236, 236, 236));
        harga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        harga.setForeground(new java.awt.Color(36, 36, 36));
        harga.setBorder(null);
        harga.setOpaque(false);
        jPanel2.add(harga);
        harga.setBounds(50, 660, 190, 30);

        kd_bar.setBackground(new java.awt.Color(236, 236, 236));
        kd_bar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kd_bar.setForeground(new java.awt.Color(36, 36, 36));
        kd_bar.setBorder(null);
        kd_bar.setOpaque(false);
        jPanel2.add(kd_bar);
        kd_bar.setBounds(50, 660, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
        jam();
        tgl();
          DefaultTableModel cartmodel = (DefaultTableModel) tbl_cart.getModel();
        if (bayar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bayar masih kosong");
        } else {
        if (cartmodel.getRowCount ()==0) {
            JOptionPane.showMessageDialog(this, "Keranjang masih kosong");
        } else {
            String ee = bayar.getText().replaceAll(",","");
        Double ff = Double.parseDouble(ee);
        String eee = g_total.getText().replace("Rp", "").replaceAll("\\.","");
        Double fff = Double.parseDouble(eee);
        Double balikan = ff-fff;
            String id_transaksi = txttransaksi.getText(), id_bar, jml, st, total_harga;
            if (ff<fff) {
                JOptionPane.showMessageDialog(this, "Uang tunai kurang");
            } else {
            try {
                String b = g_total.getText().replace("Rp.", "").replaceAll("\\." , "");
                Double c = Double.parseDouble(b);
            
                java.sql.Connection conn=(Connection)Config.configDB();
//                java.sql.Statement stm=conn.createStatement();
                String sqll = "insert into tranksaksi (`id_tranksaksi`, `tanggal_tranksaksi`, `jam_transaksi`, "
                        + "`total_bayar`,`uang`,`kembalian`, `id_anggota`, `nama_pembeli`) values ('"+id_transaksi+"', CURRENT_DATE, CURRENT_TIME, '"
                        +c+"','"+ff+"', '"+balikan+"','"+namakasir.getText()+"', '"+nama.getText()+"') ;";
                java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
                pstl.execute();
                for(int i=0;i<cartmodel.getRowCount();i++) {
                    id_bar = cartmodel.getValueAt(i, 1).toString();
                    jml = cartmodel.getValueAt(i, 3).toString();
                    st = cartmodel.getValueAt(i, 4).toString();
                    total_harga = cartmodel.getValueAt(i, 5).toString().replace("Rp.", "").replaceAll("\\.", "");
                    double g_tot = Double.parseDouble(total_harga);
                    
                    String sql = "insert into detail_tranksaksi (`id_tranksaksi`, `id_barang`, "
//                            + "`qty`, `id_satuan`, `harga_total`) values ('?', '?', '?', '?', '?') ;";
                            + "`qty`, `id_satuan`, `harga_total`) values ('"+id_transaksi+"', '"+id_bar+"', '"+jml+"', '"+st+"', '"+g_tot+"') ;";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            try {
            String sql ="TRUNCATE TABLE cart;";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
//            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        String balika = String.valueOf(balikan);
        kasir.Popup_transaksi popup = new kasir.Popup_transaksi();
        popup.trans.setText(txttransaksi.getText());
        popup.tanggal.setText(tgl.getText());
        popup.namaPelanggan.setText(nama.getText());
        popup.namaPegawai.setText(namakasir.getText());
        popup.gtot.setText(g_total.getText());
        popup.bayarp.setText(bayar.getText());
        popup.balik.setText(balika); 
        this.dispose();
        this.setVisible(true);
        grand_total();
        nama.setText(null);
        bayar.setText(null);
        popup.setVisible(true);
        
        }
        }
        }

    }//GEN-LAST:event_btn_prosesActionPerformed

    private void btn_addcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcartActionPerformed
        // TODO add your handling code here:
        Double stok = null, jml;
        String kdbar = null;
        try {
            String sqll = "SELECT jumlah FROM barang where id_barang='"+kd_bar.getText()+"' ;";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sqll);
            res.next();
            stok = res.getDouble("jumlah");
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
        jml = Double.parseDouble(jumlah.getText());
        if (stok < jml) {
            JOptionPane.showMessageDialog(this,"Maaf, Stok tidak Mencukupi");
            jumlah.setText("");
        } else {
            try {
            String sqll = "SELECT id_barang FROM cart where id_barang='"+kd_bar.getText()+"' ;";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sqll);
            res.next();
            kdbar = res.getString("id_barang");
            } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
            }
            if (kd_bar.getText().equals(kdbar)) {
                JOptionPane.showMessageDialog(null, "Barang sudah ada dalam Cart, Maka jumlah barang ditambah");
                try { 
                     String sqll = "SELECT harga_jual FROM barang where id_barang='"+kd_bar.getText()+"' ;";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sqll);
            res.next();
            Double nilai = res.getDouble("harga_jual");
            String jmll = jumlah.getText();
            Double juml = Double.parseDouble(jmll);
            
            
            Double total = juml * nilai;
            
            String sql = "Update cart set qty=qty+"+jumlah.getText()+", total_harga=total_harga+"+total+" where id_barang='"+kd_bar.getText()+"' ;" ;
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();

//            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        load_table1();
        tablestyle();
        grand_total();
        kosong();
        jam();
        tgl();
        txtcari.setText(null);                
            } else {
        try {
            String sqll = "SELECT harga_jual FROM barang where id_barang='"+kd_bar.getText()+"' ;";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sqll);
            res.next();
            Double nilai = res.getDouble("harga_jual");
            String jmll = jumlah.getText();
            Double juml = Double.parseDouble(jmll);
            
            
            Double total = juml * nilai;
            
            String sql = "INSERT INTO cart VALUES ('"+txttransaksi.getText()+"','"+kd_bar.getText()+"','"
            +jumlah.getText()+"','"+satuan.getText()+"','"+
            total+"')";
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();

//            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        load_table1();
        tablestyle();
        grand_total();
        kosong();
        jam();
        tgl();
        txtcari.setText(null);
        }
        }
    }//GEN-LAST:event_btn_addcartActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        kasir.menu_kasir nama= new kasir.menu_kasir();
        nama.nama_kasir.setText(namakasir.getText());
         
        nama.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
//        this.setVisible(false);
//        new login.logout().setVisible(true);
        int response = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new login.login().setVisible(true);
        } else if (response == JOptionPane.NO_OPTION) {
            
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        kasir.edit_barang nama= new kasir.edit_barang();
        nama.namakasir.setText(namakasir.getText());
         
        nama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        kasir.Statistik nama= new kasir.Statistik();
        nama.namakasir.setText(namakasir.getText());
         
        nama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        kasir.riwayat nama= new kasir.riwayat();
        nama.namakasir.setText(namakasir.getText());
         
        nama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jamAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jamAncestorAdded
        // TODO add your handling code here:
        jam();
    }//GEN-LAST:event_jamAncestorAdded

    private void tglAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tglAncestorAdded
        // TODO add your handling code here:
        tgl();
    }//GEN-LAST:event_tglAncestorAdded

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
        // TODO add your handling code here:
        int baris = tbl_barang.rowAtPoint(evt.getPoint());
        String id = tbl_barang.getValueAt(baris, 1).toString();
        kd_bar.setText(id);
        if (tbl_barang.getValueAt(baris, 5)==null) {
            satuan.setText("");
        } else {
            satuan.setText(tbl_barang.getValueAt(baris, 5).toString());
        }
        if (tbl_barang.getValueAt(baris, 3)==null) {
            harga.setText("");
        } else {
            harga.setText(tbl_barang.getValueAt(baris, 3).toString());
        }
//        try {
//        
//        String sql = "SELECT id_satuan FROM `barang` where id_barang='"+(tbl_barang.getValueAt(baris, 1).toString())+"';";
//        java.sql.Connection conn=(Connection)Config.configDB();
//        java.sql.Statement stm=conn.createStatement();
//        java.sql.ResultSet res=stm.executeQuery(sql);
//        satuan.setText(res.getString(1));
//        } catch (Exception e) {
//        }
                
    }//GEN-LAST:event_tbl_barangMouseClicked

    private void txttransaksiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txttransaksiAncestorAdded
        // TODO add your handling code here:
        AUTONOMORPENJUALAN();
        load_table1();
        tablestyle1();
    }//GEN-LAST:event_txttransaksiAncestorAdded

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (kd_bar_cart.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "pilih dahulu data yang ingin dihapus");
        } else {
        try {
            String sql ="delete from cart where id_barang ='"+kd_bar_cart.getText()+"' ;";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Keranjang berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table1();
        tablestyle1();
        grand_total();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cartMouseClicked
        // TODO add your handling code here:
        int baris = tbl_cart.rowAtPoint(evt.getPoint());
        String id = tbl_cart.getValueAt(baris, 1).toString();
        kd_bar_cart.setText(id);
    }//GEN-LAST:event_tbl_cartMouseClicked

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        // TODO add your handling code here:
        if (bayar.getText().equals("")) {
        } else {
            String sbyr = bayar.getText().replaceAll("\\,","");
        double dbyr = Double.parseDouble(sbyr);
        DecimalFormat df = new DecimalFormat("#,###,###");
        if(dbyr>999){
        bayar.setText(df.format(dbyr));
        }
        }
        jam();
    }//GEN-LAST:event_bayarKeyReleased

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
    
        model.addColumn("No");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Stok");
        model.addColumn("satuan");

  
    try {
        int no=1;
        String sql = "SELECT id_barang, nama_barang, harga_jual, jumlah, id_satuan FROM `barang` where nama_barang like '%" + txtcari.getText() + "%'";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
            model.addRow (new Object[] {no++,res.getString(1),
                res.getString(2),this.formatRupiah((int) res.getDouble(3)).replace(",00", ""),
                res.getString(4),res.getString(5)
            });
        }
        tbl_barang.setModel(model);
    } catch (Exception e) {
      
    }
    tablestyle();
    }//GEN-LAST:event_txtcariKeyPressed

    private void jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyReleased
        // TODO add your handling code here:
        Double stok = null, jml;
        if (kd_bar.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Silakan pilih barang terlebih dahulu");
            jumlah.setText("");
        }
    }//GEN-LAST:event_jumlahKeyReleased

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseMoved
        private void AUTONOMORPENJUALAN() {
        try {
            //--> melakukan eksekusi query untuk mengambil data dari tabel
            String sql = "SELECT MAX(id_tranksaksi) FROM tranksaksi" ;
//            Statement st = con.createStatement();
//            ResultSet rsjual = st.executeQuery(sql);
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    txttransaksi.setText("000001");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int NomorJual = no.length();
                    //MENGATUR jumlah 0
                    for (int j = 0; j < 6 - NomorJual; j++) {
                        no = "0" + no;
                    }
                    txttransaksi.setText(no);
                }
            }
            rs.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                    "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }    
    private void tablestyle() {
        JTableHeader style = tbl_barang.getTableHeader();
        tbl_barang.setRowHeight(25);
        TableColumn col=tbl_barang.getColumnModel().getColumn(0);
        col.setPreferredWidth(30);
        TableColumn col1=tbl_barang.getColumnModel().getColumn(1);
        col1.setPreferredWidth(70);
        TableColumn col2=tbl_barang.getColumnModel().getColumn(2);
        col2.setPreferredWidth(150);
        TableColumn col3=tbl_barang.getColumnModel().getColumn(3);
        col3.setPreferredWidth(90);
        TableColumn col4=tbl_barang.getColumnModel().getColumn(4);
        col4.setPreferredWidth(40);
        TableColumn col5=tbl_barang.getColumnModel().getColumn(5);
        col5.setPreferredWidth(50);

        }
    private void tablestyle1() {
        JTableHeader style = tbl_cart.getTableHeader();
        tbl_cart.setRowHeight(25);
        TableColumn col=tbl_cart.getColumnModel().getColumn(0);
        col.setPreferredWidth(30);
        TableColumn col1=tbl_cart.getColumnModel().getColumn(1);
        col1.setPreferredWidth(80);
        TableColumn col2=tbl_cart.getColumnModel().getColumn(2);
        col2.setPreferredWidth(150);
        TableColumn col3=tbl_cart.getColumnModel().getColumn(3);
        col3.setPreferredWidth(40);
        TableColumn col4=tbl_cart.getColumnModel().getColumn(4);
        col4.setPreferredWidth(40);
        TableColumn col5=tbl_cart.getColumnModel().getColumn(5);
        col5.setPreferredWidth(100);

        }
        
    public void load_table() {
    DefaultTableModel model = new DefaultTableModel();
    
        model.addColumn("No");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Stok");
        model.addColumn("satuan");

  
    try {
        int no=1;
        String sql = "SELECT id_barang, nama_barang, harga_jual, jumlah, id_satuan FROM `barang`";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
            model.addRow (new Object[] {no++,res.getString(1),
                res.getString(2),this.formatRupiah((int) res.getDouble(3)).replace(",00", ""),
                res.getString(4),res.getString(5)
            });
        }
        tbl_barang.setModel(model);
    } catch (Exception e) {
      
    }
    load_table1();
    tablestyle1();
    }
    
    public void load_table1() {
    DefaultTableModel model = new DefaultTableModel();
    
    model.addColumn("No");
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Jumlah");
    model.addColumn("Satuan");
    model.addColumn("Harga");


    
    try {
        int no=1;
        String sql = "SELECT cart.id_barang, barang.nama_barang, cart.qty, cart.id_satuan, cart.total_harga from `cart`"
               +"join barang on cart.id_barang=barang.id_barang "
                + "where cart.id_tranksaksi="+txttransaksi.getText()+" ;";
//        String sql = "SELECT * from detail_tranksaksi;";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
            model.addRow (new Object[] {no++,res.getString(1),
                res.getString(2),res.getString(3),res.getString(4),
                this.formatRupiah(res.getInt(5)).replace(",00", "")
            });
        }
        tbl_cart.setModel(model);
    } catch (Exception e) {
        
    }
    tablestyle1();
    }
    
    private void kosong(){
        kd_bar.setText(null);
        jumlah.setText(null);
        harga.setText(null);
        satuan.setText(null);
    }
    private void tgl() {
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    LocalDateTime tanggal = LocalDateTime.now();
    tgl.setText(dtf.format(tanggal));
}
    private void jam() {
    DateTimeFormatter dtf1 = DateTimeFormatter.ofPattern("HH:mm");
    LocalDateTime time = LocalDateTime.now();
    jam.setText(dtf1.format(time));
}

    private void grand_total() {
         try { 
            String sql = "SELECT sum(total_harga) as grand_total from cart "
                    + "where cart.id_tranksaksi="+txttransaksi.getText()+" ;";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            rs.next();
            g_total.setText(this.formatRupiah((int) rs.getDouble("grand_total")).replace(",00", ""));

            } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private String formatRupiah(int value){
      DecimalFormat formater = (DecimalFormat) DecimalFormat.getCurrencyInstance();
      DecimalFormatSymbols simbol = formater.getDecimalFormatSymbols();
      
      simbol.setCurrencySymbol("Rp. ");
      simbol.setMonetaryDecimalSeparator(',');// belakang sendiri pada format rupiah
      simbol.setGroupingSeparator('.');
      formater.setDecimalFormatSymbols(simbol);
      return formater.format(value);
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JButton btn_addcart;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_proses;
    private javax.swing.JLabel g_total;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jam;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kd_bar;
    private javax.swing.JLabel kd_bar_cart;
    private javax.swing.JTextField nama;
    public javax.swing.JLabel namakasir;
    private javax.swing.JLabel satuan;
    private javax.swing.JTable tbl_barang;
    private javax.swing.JTable tbl_cart;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField txtcari;
    private javax.swing.JLabel txttransaksi;
    // End of variables declaration//GEN-END:variables
}
